# docker-compose.yml
version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_escola_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escola_ocorrencias_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: